/**
 * Nümunə istehsalçı və rayon məlumatları (azexport tipli kataloq üçün).
 * Məhsul sayları MOCK_PRODUCTS üzərindən hesablanır.
 */

export type ManufacturerLegalType = "fiziki" | "huquqi";

export interface MockManufacturer {
  id: string;
  name: string;
  legalType: ManufacturerLegalType;
  /** Ölkədaxili çatdırılma təklif edir */
  domesticDelivery: boolean;
  /** Xidmət göstərilən rayonlar (boş = bütün ölkə) */
  regions: string[];
}

/** Azərbaycan üzrə rayon/siyahı — axtarış üçün eyni formatda */
export const RAYON_AZ_LIST: string[] = [
  "Abşeron rayonu",
  "Ağdam rayonu",
  "Ağdaş rayonu",
  "Ağcabədi rayonu",
  "Ağstafa rayonu",
  "Ağsu rayonu",
  "Astara rayonu",
  "Babək rayonu",
  "Bakı şəhəri Qaradağ rayonu",
  "Bakı şəhəri Nərimanov rayonu",
  "Bakı şəhəri Nəsimi rayonu",
  "Bakı şəhəri Nizami rayonu",
  "Bakı şəhəri Pirallahı rayonu",
  "Bakı şəhəri Səbail rayonu",
  "Bakı şəhəri Sabunçu rayonu",
  "Bakı şəhəri Suraxanı rayonu",
  "Bakı şəhəri Xəzər rayonu",
  "Bakı şəhəri Yasamal rayonu",
  "Balakən rayonu",
  "Bərdə rayonu",
  "Beyləqan rayonu",
  "Biləsuvar rayonu",
  "Daşkəsən rayonu",
  "Füzuli rayonu",
  "Gədəbəy rayonu",
  "Gəncə şəhəri",
  "Qobustan rayonu",
  "Goranboy rayonu",
  "Göyçay rayonu",
  "Göygöl rayonu",
  "Hacıqabul rayonu",
  "İmişli rayonu",
  "İsmayıllı rayonu",
  "Cəbrayıl rayonu",
  "Cəlilabad rayonu",
  "Culfa rayonu",
  "Kəlbəcər rayonu",
  "Kəngərli rayonu",
  "Kəpəz rayonu",
  "Xaçmaz rayonu",
  "Xankəndi şəhəri",
  "Xızı rayonu",
  "Xocalı rayonu",
  "Xocavənd rayonu",
  "Kürdəmir rayonu",
  "Laçın rayonu",
  "Lənkəran rayonu",
  "Lerik rayonu",
  "Masallı rayonu",
  "Mingəçevir şəhəri",
  "Naftalan şəhəri",
  "Naxçıvan şəhəri",
  "Neftçala rayonu",
  "Nizami rayonu",
  "Oğuz rayonu",
  "Ordubad rayonu",
  "Qəbələ rayonu",
  "Qax rayonu",
  "Qazax rayonu",
  "Quba rayonu",
  "Qubadlı rayonu",
  "Qusar rayonu",
  "Saatlı rayonu",
  "Sabirabad rayonu",
  "Sədərək rayonu",
  "Salyan rayonu",
  "Samux rayonu",
  "Şabran rayonu",
  "Şahbuz rayonu",
  "Şəki rayonu",
  "Şamaxı rayonu",
  "Şəmkir rayonu",
  "Şərur rayonu",
  "Şirvan şəhəri",
  "Şuşa rayonu",
  "Siyəzən rayonu",
  "Sumqayıt şəhəri",
  "Tərtər rayonu",
  "Tovuz rayonu",
  "Ucar rayonu",
  "Yardımlı rayonu",
  "Yevlax rayonu",
  "Zəngilan rayonu",
  "Zaqatala rayonu",
  "Zərdab rayonu",
];

export const MOCK_MANUFACTURERS: MockManufacturer[] = [
  {
    id: "mfg-asp-glass",
    name: "ASPİ GLASS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ",
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Sumqayıt şəhəri", "Bakı şəhəri Xəzər rayonu", "Abşeron rayonu"],
  },
  {
    id: "mfg-aqro",
    name: '"AQRO-AZƏRİNVEST" MMC',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Bakı şəhəri Nəsimi rayonu", "Qəbələ rayonu", "Şəki rayonu"],
  },
  {
    id: "mfg-azeripek",
    name: '"AZƏRİPƏK" AÇIQ SƏHMDAR CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Bakı şəhəri Yasamal rayonu", "Gəncə şəhəri"],
  },
  {
    id: "mfg-gilan-fmcg",
    name: '"GİLAN FMCG TRADE AND DİSTRİBUTİON" MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Bakı şəhəri Nərimanov rayonu", "Lənkəran rayonu", "Masallı rayonu"],
  },
  {
    id: "mfg-mardeli",
    name: "MƏRDƏLİ ƏKPƏR OĞLU",
    legalType: "fiziki",
    domesticDelivery: false,
    regions: ["Şamaxı rayonu"],
  },
  {
    id: "mfg-xezhangul",
    name: "XƏZANGÜL AĞƏLİ QIZI",
    legalType: "fiziki",
    domesticDelivery: true,
    regions: ["Bakı şəhəri Sabunçu rayonu"],
  },
  {
    id: "mfg-iffa",
    name: '"İFFA-2010" MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Yevlax rayonu", "Göyçay rayonu", "Ucar rayonu"],
  },
  {
    id: "mfg-ufe",
    name: '"U.F.E. SHİPPİNG" MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Bakı şəhəri Nizami rayonu", "Xaçmaz rayonu"],
  },
  {
    id: "mfg-nadir-toxum",
    name: '"NADİR QULİYEV ADINA BAKI-TAXIL" AÇIQ SƏHMDAR CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Bərdə rayonu", "Tərtər rayonu"],
  },
  {
    id: "mfg-sabirabad-konserv",
    name: '"SABİRABAD-KONSERV" AÇIQ SƏHMDAR CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Sabirabad rayonu", "Salyan rayonu"],
  },
  {
    id: "mfg-sema-firma",
    name: '"SƏMA" FƏRDİ FİRMASI',
    legalType: "fiziki",
    domesticDelivery: true,
    regions: ["Bakı şəhəri Səbail rayonu"],
  },
  {
    id: "mfg-sunbul",
    name: '"SÜNBÜL-2012" MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Şəmkir rayonu", "Gədəbəy rayonu"],
  },
  {
    id: "mfg-amoris",
    name: "“AMORİS” MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ",
    legalType: "huquqi",
    domesticDelivery: false,
    regions: ["Bakı şəhəri Nərimanov rayonu"],
  },
  {
    id: "mfg-prosys",
    name: '"PROSYS" MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Sumqayıt şəhəri"],
  },
  {
    id: "mfg-el-plastik",
    name: '"EL-PLASTİK" MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Zaqatala rayonu", "Balakən rayonu"],
  },
  {
    id: "mfg-orison",
    name: "“ORISON GROUP” MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ",
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Bakı şəhəri Nəsimi rayonu", "Kürdəmir rayonu"],
  },
  {
    id: "mfg-berteks",
    name: "“BERTEKS” MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ",
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Astara rayonu", "Lənkəran rayonu"],
  },
  {
    id: "mfg-student-demo",
    name: "108 HORECA MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ",
    legalType: "huquqi",
    domesticDelivery: true,
    regions: ["Bakı şəhəri Yasamal rayonu", "Bakı şəhəri Nəsimi rayonu"],
  },
];

export function manufacturerById(id: string): MockManufacturer | undefined {
  return MOCK_MANUFACTURERS.find((m) => m.id === id);
}
